---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: openshift-squid
  labels:
    app: openshift-squid    
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: openshift-squid
  template:
    metadata:
      labels:
        deployment: openshift-squid
        app: openshift-squid
    spec:
      containers:
        - name: openshift-squid
          image: quay.io/ltsai/openshift-squid:latest
          ports:
            - containerPort: 3128
              protocol: TCP
              name: squid
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
---
apiVersion: v1
kind: Service
metadata:
  name: openshift-squid
  labels:
    app: openshift-squid    
spec:
  selector:
    app: openshift-squid
  ports:
    - protocol: TCP
      port: 3128
      targetPort: 3128
      name: squid
