---
apiVersion: v1
kind: ConfigMap
metadata:
  name: squid-conf
  namespace: squid
data:
  squid.conf: |-
    pid_filename /tmp/${service_name}.pid
    cache_dir null /tmp
    logfile_rotate 0

    cache_log stdio:/dev/null
    access_log stdio:/dev/stdout
    cache_store_log stdio:/dev/stdout

    http_port 3128

    auth_param basic program /usr/lib64/squid/basic_ncsa_auth /etc/squid/passwd
    auth_param basic children 5
    auth_param basic realm Squid Basic Authentication
    auth_param basic credentialsttl 24 hours
    auth_param basic casesensitive off

    acl user1 proxy_auth user1
    acl user2 proxy_auth user2

    acl user1_whitelist dstdomain "/etc/squid/whitelists/user1-whitelist.txt"
    acl user2_whitelist dstdomain "/etc/squid/whitelists/user2-whitelist.txt"

    acl http proto http
    acl port_80 port 80
    acl CONNECT method CONNECT

    http_access allow user1_whitelist user1 
    http_access allow user2_whitelist user2 

    http_access deny all
---
apiVersion: v1
kind: ConfigMap
metadata:  
  name: squid-users
  namespace: squid
data:
  passwd: |-
    user1:$apr1$gqcMB7GT$QLjghjmTLy9bQJ1vuVOES1
    user2:$apr1$cLZUDY8M$69IUUMEIxlBuK7AB1zXy51
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: squid-users-whitelist
  namespace: squid
data:
  user1-whitelist.txt: |-
    .google.com
  user2-whitelist.txt: |-
    .redhat.com
---
apiVersion: v1
kind: Service
metadata:
  name: squid
  namespace: squid
spec:
  ports:
  - name: 3128-tcp
    port: 3128
    protocol: TCP
    targetPort: 3128
  selector:
    deployment: squid
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: squid
  namespace: squid
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      deployment: squid
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        deployment: squid
    spec:
      containers:
      - image: quay.io/ltsai/openshift-squid:latest
        name: squid
        ports:
        - containerPort: 3128
          protocol: TCP
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/squid/squid.conf
          name: squid-conf
          subPath: squid.conf
        - mountPath: /etc/squid/passwd
          name: squid-users
          subPath: passwd
        - mountPath: /etc/squid/whitelists
          name: whitelist
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: squid-conf
        name: squid-conf
      - configMap:
          defaultMode: 420
          name: squid-users
        name: squid-users
      - name: whitelist
        projected:
          defaultMode: 420
          sources:
          - configMap:
              name: squid-users-whitelist---
